Update Code-Security-Analysis-Workflow.yaml

diff --git a/.github/workflows/Code-Security-Analysis-Workflow.yaml b/.github/workflows/Code-Security-Analysis-Workflow.yaml
--- a/.github/workflows/Code-Security-Analysis-Workflow.yaml
+++ b/.github/workflows/Code-Security-Analysis-Workflow.yaml
@@ -70,7 +70,7 @@ jobs:
           # Check if we can find the base branch
           if git show-ref --verify --quiet "refs/remotes/origin/$base_branch"; then
             git diff --name-only "origin/$base_branch"..."HEAD" | \
-            grep -E '\.(py|js|sh|go|php|c|cpp|rb)$' > modified_files.txt || { echo "Error detecting files"; exit 1; }
+            grep -E '\.(py|js|sh|go|php|c|cpp|rb|yaml|yml)$' > modified_files.txt || { echo "Error detecting files"; exit 1; }
             echo "Modified files: $(cat modified_files.txt)"
           else
             echo "Base branch '$base_branch' not found"
@@ -112,6 +112,7 @@ jobs:
                 *.c) scan_file "$file" "cppcheck \"$file\"" ;;
                 *.cpp) scan_file "$file" "cppcheck \"$file\"" ;;
                 *.rb) echo "Ruby file detected: $file, Skipping Brakeman due to removal." ;;
+                # *.yaml and *.yml are already being picked up
               esac
             done < modified_files.txt
           else
